/**
 * importMexicoTimesheets.ts
 * -----------------
 * Script to bulk import Timesheet records.
 * 
 * To run:
 * npx ts-node src/scripts/importMexicoTimesheets.ts
 */

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { v4 as uuidv4 } from 'uuid';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceRoleKey) {
    console.error('❌ Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env');
    process.exit(1);
}

const supabaseAdmin = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false }
});

// Set DRY_RUN to false to actually insert data into the database.
const DRY_RUN = true;

// You can define your raw data here, or read it from a file.
// If reading from a file, uncomment the following lines:
// const rawDataPath = path.resolve(__dirname, 'mx_timesheets_data.json');
// const MOCK_DATA = JSON.parse(fs.readFileSync(rawDataPath, 'utf8'));

const MOCK_DATA = [
    {
        // IMPORTANT: Replace this ID with the actual ID generated by your personnel script
        "personnelId": "REPLACE-WITH-ACTUAL-PERSONNEL-ID", 
        // IMPORTANT: Replace with an actual Project ID
        "projectId": "REPLACE-WITH-ACTUAL-PROJECT-ID",     
        "date": "2024-05-13",
        "timeIn": "08:00",
        "timeOut": "17:00",
        "hours": 9.0,
        "type": "On Site", // "On Site" | "Travel" | "Other"
        "classification": "Regular", // "Regular" | "Overtime" | "Double Time" | "Unclassified"
        "notes": "Completed wiring and grounding."
    }
];

async function run() {
    console.log(`🚀 Starting Timesheet Import... (DRY_RUN=${DRY_RUN})`);
    
    const formattedTimesheets = MOCK_DATA.map(t => {
        return {
            id: `TS-${t.date}-${uuidv4().substring(0, 8)}`, // Generate a unique traceable ID
            personnelId: t.personnelId,
            projectId: t.projectId,
            date: t.date,
            timeIn: t.timeIn,
            timeOut: t.timeOut,
            hours: t.hours,
            type: t.type,
            classification: t.classification,
            status: 'Approved', // Auto-approve imported historical timesheets
            source: 'manual', // H-04 Rule: Flag as manual entry
            manualReason: 'Initial data migration script', // H-04 Rule justification
            notes: t.notes
        };
    });

    if (DRY_RUN) {
        console.log("Dry run complete. Here is the first formatted record:");
        console.log(JSON.stringify(formattedTimesheets[0], null, 2));
        console.log(`\nTotal records prepared: ${formattedTimesheets.length}`);
        console.log("To insert into the database, change `const DRY_RUN = true;` to `false`.");
        return;
    }

    console.log(`Inserting ${formattedTimesheets.length} records into 'timesheets' table...`);
    const { data, error } = await supabaseAdmin
        .from('timesheets') // Assuming your table name is 'timesheets' in Supabase
        .insert(formattedTimesheets)
        .select();

    if (error) {
        console.error("❌ Error inserting timesheets:", error);
    } else {
        console.log("✅ Successfully inserted timesheets!");
        console.log(`Imported ${data.length} records.`);
    }
}

run().catch(console.error);
